    source "https://rubygems.org"

    gem 'test-unit', :group => [:development, :test]
    gem 'gauge-ruby' , '~>0.5.1', :group => [:development, :test]
    gem 'capybara', '~> 3.12'
    gem 'gauge-ruby' , '~>0.5.1', :group => [:development, :test]
    gem 'rspec', '~> 3.8'
    gem 'selenium-webdriver', '~> 3.141'
